name: build-and-test

on:
  push:
    branches: 
      - '*'


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v4
    - run: npm install
    - name: Generate
      run: npx tree-sitter generate
    - name: Test
      run: npx tree-sitter test
    - name: Commit parser changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "ci: parser"